=== AntoineGautier/modelica-json/schema-modelica.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "schema-modelica.json",
  "type": "array",
  "title": "JSON parsed Modelica file",
  "description": "Json representation of a Modelica model",
  "definitions": {
    "ModelicaBlock": {
      "description": "Info of a modelica block: model, parameter, input or output",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "className",
          "name"
        ],
        "properties": {
          "className": {
            "description": "Name of the class: no special characters or spaces",
            "type": "string",
            "pattern": "^([a-zA-Z0-9._*]*)$"
          },
          "name": {
            "description": "Name of the block: no special characters or spaces",
            "type": "string",
            "pattern": "^([a-zA-Z0-9._*]*)$"
          },
          "comment": {
            "description": "comment on the block: no special characters or spaces",
            "type": "string"
          },
          "value": {
            "description": "value of the block, if applicable",
            "type": "string"
          },
          "annotation": {
            "type": "object",
            "required": [
              "dialog"
            ],
            "properties": {
              "dialog": {
                "type": "object",
                "properties": {
                  "tab": {
                    "type": "string",
                    "examples": [
                      "General"
                    ]
                  },
                  "group": {
                    "type": "string",
                    "examples": [
                      "Parameters"
                    ]
                  }
                }
              }
            }
          },
          "modifications": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                },
                "isFinal": {
                  "type": "boolean"
                }
              }
            }
          },
          "placement": {
            "type": "object",
            "properties": {
              "transformation": {
                "type": "object",
                "properties": {
                  "extent": {
                    "$ref": "#/definitions/coordinates"
                  }
                }
              }
            }
          }
        }
      }
    },
    "coordinates": {
      "description": "Coordinates on a 2d plan",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "x1",
          "x2"
        ],
        "properties": {
          "x1": {
            "type": "number"
          },
          "x2": {
            "type": "number"
          }
        }
      }
    },
    "color": {
      "description": "RGB colors",
      "type": "object",
      "required": [
        "r",
        "g",
        "b"
      ],
      "properties": {
        "r": {
          "type": "number",
          "minimum": 0,
          "maximum": 255
        },
        "g": {
          "type": "number",
          "minimum": 0,
          "maximum": 255
        },
        "b": {
          "type": "number",
          "minimum": 0,
          "maximum": 255
        }
      }
    }
  },
  "items": {
    "type": "object",
    "required": [
      "modelicaFile",
      "topClassName"
    ],
    "properties": {
      "modelicaFile": {
        "decription": "Name of the Modelica file. Ends with '.mo'",
        "type": "string",
        "pattern": ".*.(mo|MO)"
      },
      "within": {
        "description": "Within statement from the Modelica file : no special characters or spaces",
        "type": "string",
        "pattern": "^([a-zA-Z0-9._*]*)$"
      },
      "topClassName": {
        "description": "Name of the top class of the Modelica model: no special characters or spaces ",
        "type": "string",
        "pattern": "^([a-zA-Z0-9._*]*)$"
      },
      "comment": {
        "description": "Comment on the model",
        "type": "string"
      },
      "public": {
        "type": "object",
        "description": "Public part of the modelica file",
        "properties": {
          "parameters": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "models": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "inputs": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "outputs": {
            "$ref": "#/definitions/ModelicaBlock"
          }
        }
      },
      "protected": {
        "type": "object",
        "description": "Protected part of the modelica file",
        "properties": {
          "parameters": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "models": {
            "$ref": "#/definitions/ModelicaBlock"
          }
        }
      },
      "connections": {
        "type": "array",
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "instance": {
                "type": "string"
              },
              "connector": {
                "type": "string"
              },
              "points": {
                "$ref": "#/definitions/coordinates"
              },
              "color": {
                "$ref": "#/definitions/color"
              }
            }
          }
        }
      },
      "info": {
        "description": "Informations of the model must be in html format",
        "type": "string",
        "pattern": "^(<(html|HTML)>)(.|\n)*(</(html|HTML)>)$"
      }
    }
  }
}

=== AntoineGautier/modelica-json/test/FromModelica/modelica/json/FromModelica.ParameterWithMisplacedInfo.json
[
  {
    "modelicaFile": "FromModelica/ParameterWithMisplacedInfo.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.ParameterWithMisplacedInfo",
    "comment": "Some class comment",
    "public": {
      "parameters": [
        {
          "className": "Real",
          "type": "Real",
          "name": "kP",
          "value": "1",
          "comment": "Some comment",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          }
        }
      ]
    }
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/ExtendsClause-2-simplified.json
[
  {
    "modelicaFile": "./ExtendsClause-2.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.ExtendsClause",
    "comment": "model with extends clause",
    "public": {
      "parameters": [
        {
          "name": "length",
          "comment": "Length of the pipe",
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          },
          "className": "Modelica.SIunits.Length"
        }
      ],
      "models": [
        {
          "prefix": "extends",
          "name": "Buildings.Controls.OBC.CDL.Continuous.LimPID",
          "modifications": [
            {
              "name": "k",
              "value": "2",
              "isFinal": false
            },
            {
              "name": "Ti",
              "value": "2",
              "isFinal": false
            }
          ],
          "within": "FromModelica",
          "className": "Buildings.Controls.OBC.CDL.Continuous.LimPID"
        },
        {
          "prefix": "extends",
          "name": "Buildings.Controls.OBC.CDL.Logical.TrueHoldWithReset",
          "modifications": [
            {
              "prefix": "redeclare",
              "className": "Buildings.Controls.OBC.CDL.Logical.TrueDelay",
              "name": "onDelay",
              "modifications": [
                {
                  "name": "delayTime",
                  "value": "duration",
                  "isFinal": true
                }
              ],
              "isFinal": false
            },
            {
              "name": "duration",
              "value": "300",
              "isFinal": true
            }
          ],
          "within": "FromModelica",
          "className": "Buildings.Controls.OBC.CDL.Logical.TrueHoldWithReset"
        },
        {
          "name": "gain",
          "comment": "Constant gain",
          "modifications": [
            {
              "name": "k",
              "value": "k",
              "isFinal": true
            }
          ],
          "within": "FromModelica",
          "className": "Buildings.Controls.OBC.CDL.Continuous.Gain"
        }
      ]
    },
    "protected": {
      "parameters": [
        {
          "name": "ARound",
          "value": "dh^2*Modelica.Constants.pi/4",
          "comment": "Cross sectional area (assuming a round cross section area)",
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          },
          "className": "Modelica.SIunits.Area"
        }
      ]
    },
    "info": "<html>\ntest...test...test...test...test...\n</html>"
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/modelica/json/FromModelica.Parameter1WithVendorAnnotation.json
[
  {
    "modelicaFile": "FromModelica/Parameter1WithVendorAnnotation.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.Parameter1WithVendorAnnotation",
    "comment": "Some class comment",
    "public": {
      "parameters": [
        {
          "className": "Real",
          "type": "Real",
          "name": "kP",
          "value": "1",
          "comment": "Some comment",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            },
            "__cdl": {
              "haystack": {
                "dis": "site",
                "area": "400"
              },
              "brick": "xxxxx",
              "point": "digital"
            }
          }
        }
      ]
    }
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/modelica/simplified/FromModelica.BlockInputOutput.json
[
  {
    "modelicaFile": "FromModelica/BlockInputOutput.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.BlockInputOutput",
    "comment": "A block with an input and an output signal",
    "public": {
      "inputs": [
        {
          "className": "Buildings.Controls.OBC.CDL.Interfaces.RealInput",
          "name": "u",
          "comment": "Input connector",
          "placement": {
            "transformation": {
              "extent": [
                {
                  "x1": -140,
                  "x2": -20
                },
                {
                  "x1": -100,
                  "x2": 20
                }
              ]
            },
            "iconTransformation": {
              "extent": [
                {
                  "x1": -140,
                  "x2": -20
                },
                {
                  "x1": -100,
                  "x2": 20
                }
              ]
            }
          }
        }
      ],
      "outputs": [
        {
          "className": "Buildings.Controls.OBC.CDL.Interfaces.RealOutput",
          "name": "y",
          "comment": "Output connector",
          "placement": {
            "transformation": {
              "extent": [
                {
                  "x1": 100,
                  "x2": -10
                },
                {
                  "x1": 120,
                  "x2": 10
                }
              ]
            }
          }
        }
      ]
    }
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/modelica/json/FromModelica.Parameter2.json
[
  {
    "modelicaFile": "FromModelica/Parameter2.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.Parameter2",
    "comment": "Some class comment",
    "public": {
      "parameters": [
        {
          "className": "Real",
          "type": "Real",
          "name": "myPar1",
          "value": "1",
          "comment": "Some comment",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          }
        },
        {
          "className": "Real",
          "type": "Real",
          "name": "myParNoValue",
          "comment": "Some comment",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          }
        },
        {
          "className": "Real",
          "type": "Real",
          "name": "myParMin",
          "comment": "Some comment",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "min": {
            "value": "0"
          },
          "modifications": [
            {
              "value": "0",
              "isFinal": false
            }
          ],
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          }
        },
        {
          "className": "Real",
          "type": "Real",
          "name": "myParMax",
          "comment": "Some comment",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "max": {
            "value": "0"
          },
          "modifications": [
            {
              "value": "0",
              "isFinal": false
            }
          ],
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          }
        },
        {
          "className": "Real",
          "type": "Real",
          "name": "myParUnit",
          "comment": "Some comment",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "modifications": [
            {
              "value": "\"K\"",
              "isFinal": false
            }
          ],
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          }
        },
        {
          "className": "Real",
          "type": "Real",
          "name": "myParInGroup",
          "comment": "Some comment",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "annotation": {
            "dialog": {
              "group": "Gains",
              "tab": "General"
            }
          }
        },
        {
          "className": "Real",
          "type": "Real",
          "name": "myParInTab",
          "comment": "Some comment",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "annotation": {
            "dialog": {
              "tab": "Initialization tab",
              "group": "Parameters"
            }
          }
        },
        {
          "className": "Real",
          "type": "Real",
          "name": "myParInTabInGroup1",
          "comment": "Some comment 1",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "annotation": {
            "dialog": {
              "tab": "Initialization tab",
              "group": "Initial state"
            }
          }
        },
        {
          "className": "Real",
          "type": "Real",
          "name": "myParInTabInGroup2",
          "comment": "Some comment 2",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "annotation": {
            "dialog": {
              "tab": "Initialization tab",
              "group": "Initial state"
            }
          }
        }
      ]
    }
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/ExtendsClause-3-simplified.json
[
  {
    "modelicaFile": "./ExtendsClause-3.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.ExtendsClause",
    "comment": "model with extends clause",
    "public": {
      "parameters": [
        {
          "name": "length",
          "comment": "Length of the pipe",
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          },
          "className": "Modelica.SIunits.Length"
        }
      ],
      "models": [
        {
          "prefix": "extends",
          "name": "Buildings.Controls.OBC.CDL.Constants",
          "within": "FromModelica",
          "className": "Buildings.Controls.OBC.CDL.Constants"
        },
        {
          "prefix": "extends",
          "name": "Buildings.Controls.OBC.CDL.Logical.TrueHoldWithReset",
          "modifications": [
            {
              "name": "duration",
              "value": "300",
              "isFinal": true
            }
          ],
          "within": "FromModelica",
          "className": "Buildings.Controls.OBC.CDL.Logical.TrueHoldWithReset"
        },
        {
          "name": "gain",
          "comment": "Constant gain",
          "modifications": [
            {
              "name": "k",
              "value": "k",
              "isFinal": true
            }
          ],
          "within": "FromModelica",
          "className": "Buildings.Controls.OBC.CDL.Continuous.Gain"
        }
      ]
    },
    "protected": {
      "parameters": [
        {
          "name": "ARound",
          "value": "dh^2*Modelica.Constants.pi/4",
          "comment": "Cross sectional area (assuming a round cross section area)",
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          },
          "className": "Modelica.SIunits.Area"
        }
      ]
    },
    "info": "<html>\ntest...test...test...test...test...\n</html>"
  }
]
