=== AntoineGautier/modelica-json/schema-CDL.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "schema-modelica.json",
  "type": "array",
  "title": "JSON parsed Modelica file",
  "description": "Json representation of a Modelica model",
  "definitions": {
    "ModelicaBlock": {
      "description": "Info of a modelica block: model, parameter, input or output",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "className",
          "name"
        ],
        "properties": {
          "className": {
            "description": "Name of the class: no special characters or spaces",
            "type": "string",
            "pattern": "^([a-zA-Z0-9._*]*)$"
          },
          "name": {
            "description": "Name of the block: no special characters or spaces",
            "type": "string",
            "pattern": "^([a-zA-Z0-9._*]*)$"
          },
          "comment": {
            "description": "comment on the block: no special characters or spaces",
            "type": "string"
          },
          "value": {
            "description": "value of the block, if applicable",
            "type": "string"
          },
          "annotation": {
            "type": "object",
            "required": [
              "dialog"
            ],
            "properties": {
              "dialog": {
                "type": "object",
                "properties": {
                  "tab": {
                    "type": "string",
                    "examples": [
                      "General"
                    ]
                  },
                  "group": {
                    "type": "string",
                    "examples": [
                      "Parameters"
                    ]
                  }
                }
              }
            }
          },
          "modifications": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                },
                "isFinal": {
                  "type": "boolean"
                }
              }
            }
          },
          "placement": {
            "type": "object",
            "properties": {
              "transformation": {
                "type": "object",
                "properties": {
                  "extent": {
                    "$ref": "#/definitions/coordinates"
                  }
                }
              }
            }
          }
        }
      }
    },
    "coordinates": {
      "description": "Coordinates on a 2d plan",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "x1",
          "x2"
        ],
        "properties": {
          "x1": {
            "type": "number"
          },
          "x2": {
            "type": "number"
          }
        }
      }
    },
    "GraphicalBlock":{
      "type":"object",
      "properties": {
        "extent": {
          "$ref": "#/definitions/coordinates"
        },
        "coordinate":{
          "$ref": "#/definitions/coordinates"
        },
        "preserveAspectRatio":{
          "type": "boolean"
        },
        "initialScale":{
          "type":"number",
          "minimum": 0
        },
        "items":{
          "type":"object",
          "required": ["width","height"],
          "properties": {
            "width":{
              "type":"number",
              "minimum": 0
            },
            "height":{
              "type":"number",
              "minimum": 0
            },
            "hasDots":{
              "type":"boolean"
            },
            "layerPolygons":{
              "type":"array",
              "items": {
                "type":"object",
                "required": ["points","hasFill","fill","stroke","strokeWidth","strokeDasharray"],
                "properties": {
                  "points":{
                    "type":"string",
                    "pattern": "[0-9, ]*"
                  },
                  "hasFill":{
                    "type":"boolean"
                  },
                  "fill":{
                    "type":"string"                  },
                  "stroke":{
                    "type":"string"                  },
                  "strokeWidth": {
                    "type":"number",
                    "minimum": 0
                  },
                  "strokeDasharray":{
                    "type":"string",
                    "pattern": "[0-9, ]*"
                  }
                }
              }
            }
          }
        },
        "drawing":{
          "type":"string",
          "pattern": "^(<(svg|SVG))(.|\n)*(</(svg|SVG)>)$"
        }
      }
    },
    "color": {
      "description": "RGB colors",
      "type": "object",
      "required": [
        "r",
        "g",
        "b"
      ],
      "properties": {
        "r": {
          "type": "number",
          "minimum": 0,
          "maximum": 255
        },
        "g": {
          "type": "number",
          "minimum": 0,
          "maximum": 255
        },
        "b": {
          "type": "number",
          "minimum": 0,
          "maximum": 255
        }
      }
    }
  },
  "items": {
    "type": "object",
    "required": [
      "modelicaFile",
      "topClassName",
      "icon",
      "svg",
      "diagram"
    ],
    "properties": {
      "modelicaFile": {
        "decription": "Name of the Modelica file. Ends with '.mo'",
        "type": "string",
        "pattern": ".*.(mo|MO)"
      },
      "within": {
        "description": "Within statement from the Modelica file : no special characters or spaces",
        "type": "string",
        "pattern": "^([a-zA-Z0-9._*]*)$"
      },
      "topClassName": {
        "description": "Name of the top class of the Modelica model: no special characters or spaces ",
        "type": "string",
        "pattern": "^([a-zA-Z0-9._*]*)$"
      },
      "comment": {
        "description": "Comment on the model",
        "type": "string"
      },
      "public": {
        "type": "object",
        "description": "Public part of the modelica file",
        "properties": {
          "parameters": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "models": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "inputs": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "outputs": {
            "$ref": "#/definitions/ModelicaBlock"
          }
        }
      },
      "protected": {
        "type": "object",
        "description": "Protected part of the modelica file",
        "properties": {
          "parameters": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "models": {
            "$ref": "#/definitions/ModelicaBlock"
          }
        }
      },
      "connections": {
        "type": "array",
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "instance": {
                "type": "string"
              },
              "connector": {
                "type": "string"
              },
              "points": {
                "$ref": "#/definitions/coordinates"
              },
              "color": {
                "$ref": "#/definitions/color"
              }
            }
          }
        }
      },
      "info": {
        "description": "Informations of the model must be in html format",
        "type": "string",
        "pattern": "^(<(html|HTML)>)(.|\n)*(</(html|HTML)>)$"
      },
      "icon": {
        "type":"object",
        "required": ["coordinateSystem"],
        "properties": {
          "coordinateSystem":{
            "allOf": [
              {"$ref": "#/definitions/GraphicalBlock"},
              {"required": ["extent", "preserveAspectRatio"]}
            ]
          }
        }
      },
      "svg": {
        "type":"object",
        "properties": {
          "icon":{
            "allOf": [
              {"$ref": "#/definitions/GraphicalBlock"},
              {"required": ["items", "initialScale", "preserveAspectRatio","drawing"]}
            ]
          },
          "diagram":{
            "allOf": [
              {"$ref": "#/definitions/GraphicalBlock"},
              {"required": ["items", "preserveAspectRatio","drawing"]}
            ]
          }
        }
      },
      "diagram":{
        "type":"object",
        "properties": {
          "coordinateSystem":{
            "allOf": [
              {"$ref": "#/definitions/GraphicalBlock"},
              {"required": ["extent", "preserveAspectRatio"]}
            ]
          }
        }
      }
    }
  }
}

=== AntoineGautier/modelica-json/test/FromModelica/cdl/simplified/FromModelica.Parameter1WithVendorAnnotation.json
[
  {
    "modelicaFile": "./Parameter1WithVendorAnnotation.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.Parameter1WithVendorAnnotation",
    "comment": "Some class comment",
    "public": {
      "parameters": [
        {
          "className": "Real",
          "name": "kP",
          "value": "1",
          "comment": "Some comment",
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            },
            "__cdl": {
              "haystack": {
                "dis": "site",
                "area": "400"
              },
              "brick": "xxxxx",
              "point": "digital"
            }
          }
        }
      ]
    },
    "icon": {
      "coordinateSystem": {
        "extent": [
          {
            "x1": -100,
            "x2": -100
          },
          {
            "x1": 100,
            "x2": 100
          }
        ],
        "preserveAspectRatio": true,
        "initialScale": 0.1
      }
    },
    "svg": {
      "icon": {
        "items": {
          "width": 200,
          "height": 200,
          "hasDots": false
        },
        "coordinate": [
          {
            "x1": 0,
            "x2": 200
          },
          {
            "x1": 200,
            "x2": 0
          }
        ],
        "initialScale": 0.1,
        "preserveAspectRatio": true,
        "drawing": "<svg version=\"1.1\" baseProfile=\"full\" width=\"200mm\" height=\"200mm\"\n     viewBox=\"0 0 200 200\" xmlns=\"http://www.w3.org/2000/svg\">\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n</svg>"
      },
      "diagram": {
        "items": {
          "width": 200,
          "height": 200,
          "hasDots": false
        },
        "initialScale": 0.1,
        "preserveAspectRatio": true,
        "drawing": "<svg version=\"1.1\" baseProfile=\"full\" width=\"200mm\" height=\"200mm\"\n     viewBox=\"0 0 200 200\" xmlns=\"http://www.w3.org/2000/svg\">\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n</svg>"
      }
    },
    "diagram": {
      "coordinateSystem": {
        "extent": [
          {
            "x1": -100,
            "x2": -100
          },
          {
            "x1": 100,
            "x2": 100
          }
        ],
        "preserveAspectRatio": true,
        "initialScale": 0.1
      }
    }
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/cdl/json/FromModelica.package.json
[
  {
    "modelicaFile": "./package.mo",
    "within": "",
    "topClassName": "FromModelica",
    "comment": "Package with test models",
    "public": {
      "models": [
        {
          "className": "Integer",
          "name": "one",
          "value": "1",
          "comment": "An integer constant with value 1"
        }
      ]
    },
    "icon": {
      "coordinateSystem": {
        "extent": [
          {
            "x1": -100,
            "x2": -100
          },
          {
            "x1": 100,
            "x2": 100
          }
        ],
        "preserveAspectRatio": true,
        "initialScale": 0.1
      }
    },
    "svg": {
      "icon": {
        "items": {
          "width": 200,
          "height": 200,
          "hasDots": false
        },
        "coordinate": [
          {
            "x1": 0,
            "x2": 200
          },
          {
            "x1": 200,
            "x2": 0
          }
        ],
        "initialScale": 0.1,
        "preserveAspectRatio": true,
        "drawing": "<svg version=\"1.1\" baseProfile=\"full\" width=\"200mm\" height=\"200mm\"\n     viewBox=\"0 0 200 200\" xmlns=\"http://www.w3.org/2000/svg\">\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n</svg>"
      },
      "diagram": {
        "items": {
          "width": 200,
          "height": 200,
          "hasDots": false
        },
        "initialScale": 0.1,
        "preserveAspectRatio": true,
        "drawing": "<svg version=\"1.1\" baseProfile=\"full\" width=\"200mm\" height=\"200mm\"\n     viewBox=\"0 0 200 200\" xmlns=\"http://www.w3.org/2000/svg\">\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n</svg>"
      }
    },
    "diagram": {
      "coordinateSystem": {
        "extent": [
          {
            "x1": -100,
            "x2": -100
          },
          {
            "x1": 100,
            "x2": 100
          }
        ],
        "preserveAspectRatio": true,
        "initialScale": 0.1
      }
    }
  }
]
