=== AntoineGautier/modelica-json/schema-modelica.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "schema-modelica.json",
  "type": "array",
  "title": "JSON parsed Modelica file",
  "description": "Json representation of a Modelica model",
  "definitions": {
    "ModelicaBlock": {
      "description": "Info of a modelica block: model, parameter, input or output",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "className",
          "name"
        ],
        "properties": {
          "className": {
            "description": "Name of the class: no special characters or spaces",
            "type": "string",
            "pattern": "^([a-zA-Z0-9._*]*)$"
          },
          "name": {
            "description": "Name of the block: no special characters or spaces",
            "type": "string",
            "pattern": "^([a-zA-Z0-9._*]*)$"
          },
          "comment": {
            "description": "comment on the block: no special characters or spaces",
            "type": "string"
          },
          "value": {
            "description": "value of the block, if applicable",
            "type": "string"
          },
          "annotation": {
            "type": "object",
            "required": [
              "dialog"
            ],
            "properties": {
              "dialog": {
                "type": "object",
                "properties": {
                  "tab": {
                    "type": "string",
                    "examples": [
                      "General"
                    ]
                  },
                  "group": {
                    "type": "string",
                    "examples": [
                      "Parameters"
                    ]
                  }
                }
              }
            }
          },
          "modifications": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                },
                "isFinal": {
                  "type": "boolean"
                }
              }
            }
          },
          "placement": {
            "type": "object",
            "properties": {
              "transformation": {
                "type": "object",
                "properties": {
                  "extent": {
                    "$ref": "#/definitions/coordinates"
                  }
                }
              }
            }
          }
        }
      }
    },
    "coordinates": {
      "description": "Coordinates on a 2d plan",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "x1",
          "x2"
        ],
        "properties": {
          "x1": {
            "type": "number"
          },
          "x2": {
            "type": "number"
          }
        }
      }
    },
    "color": {
      "description": "RGB colors",
      "type": "object",
      "required": [
        "r",
        "g",
        "b"
      ],
      "properties": {
        "r": {
          "type": "number",
          "minimum": 0,
          "maximum": 255
        },
        "g": {
          "type": "number",
          "minimum": 0,
          "maximum": 255
        },
        "b": {
          "type": "number",
          "minimum": 0,
          "maximum": 255
        }
      }
    }
  },
  "items": {
    "type": "object",
    "required": [
      "modelicaFile",
      "topClassName"
    ],
    "properties": {
      "modelicaFile": {
        "decription": "Name of the Modelica file. Ends with '.mo'",
        "type": "string",
        "pattern": ".*.(mo|MO)"
      },
      "within": {
        "description": "Within statement from the Modelica file : no special characters or spaces",
        "type": "string",
        "pattern": "^([a-zA-Z0-9._*]*)$"
      },
      "topClassName": {
        "description": "Name of the top class of the Modelica model: no special characters or spaces ",
        "type": "string",
        "pattern": "^([a-zA-Z0-9._*]*)$"
      },
      "comment": {
        "description": "Comment on the model",
        "type": "string"
      },
      "public": {
        "type": "object",
        "description": "Public part of the modelica file",
        "properties": {
          "parameters": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "models": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "inputs": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "outputs": {
            "$ref": "#/definitions/ModelicaBlock"
          }
        }
      },
      "protected": {
        "type": "object",
        "description": "Protected part of the modelica file",
        "properties": {
          "parameters": {
            "$ref": "#/definitions/ModelicaBlock"
          },
          "models": {
            "$ref": "#/definitions/ModelicaBlock"
          }
        }
      },
      "connections": {
        "type": "array",
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "instance": {
                "type": "string"
              },
              "connector": {
                "type": "string"
              },
              "points": {
                "$ref": "#/definitions/coordinates"
              },
              "color": {
                "$ref": "#/definitions/color"
              }
            }
          }
        }
      },
      "info": {
        "description": "Informations of the model must be in html format",
        "type": "string",
        "pattern": "^(<(html|HTML)>)(.|\n)*(</(html|HTML)>)$"
      }
    }
  }
}

=== AntoineGautier/modelica-json/test/FromModelica/modelica/json/FromModelica.MisplacedInfoWithParameter.json
[
  {
    "modelicaFile": "FromModelica/MisplacedInfoWithParameter.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.MisplacedInfoWithParameter",
    "comment": "A block that places info section in parameter annotation",
    "public": {
      "parameters": [
        {
          "className": "Real",
          "type": "Real",
          "name": "kP",
          "value": "1",
          "comment": "Some comment",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          }
        }
      ]
    }
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/modelica/json/FromModelica.ParameterWithAttributes.json
[
  {
    "modelicaFile": "FromModelica/ParameterWithAttributes.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.ParameterWithAttributes",
    "comment": "Some class comment",
    "public": {
      "parameters": [
        {
          "className": "Real",
          "name": "kP",
          "value": "1",
          "comment": "Some comment",
          "unit": {
            "value": "\"Pa\"",
            "isFinal": false
          },
          "quantity": {
            "value": "\"PressureDifference\"",
            "isFinal": false
          },
          "min": {
            "value": "0",
            "isFinal": false
          },
          "max": {
            "value": "2",
            "isFinal": false
          },
          "nominal": {
            "value": "0.5",
            "isFinal": false
          },
          "start": {
            "value": "0.2",
            "isFinal": false
          },
          "fixed": {
            "value": "false",
            "isFinal": false
          },
          "stateSelect": {
            "value": "StateSelect.default",
            "isFinal": false
          },
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          }
        }
      ]
    },
    "info": "<html>\n<p>\nThis is the info section.\n</p>\n</html>"
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/BlockWithBlock1-simplified.json
[
  {
    "modelicaFile": "./BlockWithBlock1.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.BlockWithBlock1",
    "comment": "A block that instantiates another public and protected block",
    "public": {
      "models": [
        {
          "name": "bloPub",
          "comment": "A public block",
          "className": "Block1"
        }
      ]
    },
    "protected": {
      "models": [
        {
          "name": "bloPro",
          "comment": "A protected block",
          "className": "Block1"
        }
      ]
    }
  },
  {
    "modelicaFile": "Block1.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.Block1",
    "comment": "A block that instantiates nothing"
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/modelica/json/FromModelica.package.json
[
  {
    "modelicaFile": "FromModelica/package.mo",
    "within": "",
    "topClassName": "FromModelica",
    "comment": "Package with test models",
    "public": {
      "models": [
        {
          "className": "Integer",
          "name": "one",
          "value": "1",
          "comment": "An integer constant with value 1"
        }
      ]
    }
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/BlockInputOutput-simplified.json
[
  {
    "modelicaFile": "./BlockInputOutput.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.BlockInputOutput",
    "comment": "A block with an input and an output signal",
    "public": {
      "inputs": [
        {
          "name": "u",
          "comment": "Input connector",
          "className": "Buildings.Controls.OBC.CDL.Interfaces.RealInput"
        }
      ],
      "outputs": [
        {
          "name": "y",
          "comment": "Output connector",
          "className": "Buildings.Controls.OBC.CDL.Interfaces.RealOutput"
        }
      ]
    }
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/modelica/json/FromModelica.BlockInputOutput.json
[
  {
    "modelicaFile": "FromModelica/BlockInputOutput.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.BlockInputOutput",
    "comment": "A block with an input and an output signal",
    "public": {
      "inputs": [
        {
          "className": "Buildings.Controls.OBC.CDL.Interfaces.RealInput",
          "name": "u",
          "comment": "Input connector",
          "placement": {
            "transformation": {
              "extent": [
                {
                  "x1": -140,
                  "y1": -20
                },
                {
                  "x1": -100,
                  "y1": 20
                }
              ]
            },
            "iconTransformation": {
              "extent": [
                {
                  "x1": -140,
                  "y1": -20
                },
                {
                  "x1": -100,
                  "y1": 20
                }
              ]
            }
          }
        }
      ],
      "outputs": [
        {
          "className": "Buildings.Controls.OBC.CDL.Interfaces.RealOutput",
          "name": "y",
          "comment": "Output connector",
          "placement": {
            "transformation": {
              "extent": [
                {
                  "x1": 100,
                  "y1": -10
                },
                {
                  "x1": 120,
                  "y1": 10
                }
              ]
            }
          }
        }
      ]
    }
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/modelica/json/FromModelica.Parameter1.json
[
  {
    "modelicaFile": "FromModelica/Parameter1.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.Parameter1",
    "comment": "Some class comment",
    "public": {
      "parameters": [
        {
          "className": "Real",
          "type": "Real",
          "name": "kP",
          "value": "1",
          "comment": "Some comment",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          }
        }
      ]
    }
  }
]

=== AntoineGautier/modelica-json/test/FromModelica/modelica/json/FromModelica.ParameterWithInfo.json
[
  {
    "modelicaFile": "FromModelica/ParameterWithInfo.mo",
    "within": "FromModelica",
    "topClassName": "FromModelica.ParameterWithInfo",
    "comment": "Some class comment",
    "public": {
      "parameters": [
        {
          "className": "Real",
          "type": "Real",
          "name": "kP",
          "value": "1",
          "comment": "Some comment",
          "unit": {
            "value": "\"1\""
          },
          "displayUnit": {
            "value": "\"1\""
          },
          "annotation": {
            "dialog": {
              "tab": "General",
              "group": "Parameters"
            }
          }
        }
      ]
    },
    "info": "<html>\n<p>\nThis is the info section.\n</p>\n</html>"
  }
]
